name: rsa_encrypt
description: Enable you to quickly implement rsa encryption in your flutter app,
  it covers everything from Generating key pairs, encrypt and decrypting
  strings.
version: 1.0.5
homepage: https://github.com/AbdelbakiBoukerche/rsa_encrypt

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  asn1lib: ^1.0.0
  pointycastle: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null

# To add assets to your package, add an assets section, like this:
# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg
